# Generated by Django 5.2.3 on 2025-11-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_authoraccount_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authoraccount',
            name='image',
            field=models.URLField(default='https://unsplash.com/photos/a-woman-freelancer-working-on-laptop-sitting-on-a-pier-by-the-backyard-lake-a-concept-of-remote-office-work-during-vacation-yOuZaN3zqXc'),
        ),
    ]
