# Generated by Django 5.2.3 on 2025-11-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_authoraccount_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authoraccount',
            name='image',
            field=models.URLField(default='https://images.unsplash.com/photo-1501785888041-af3ef285b470'),
        ),
    ]
