# Generated by Django 5.2.3 on 2025-11-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_authoraccount_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authoraccount',
            name='image',
            field=models.URLField(default='https://www.freepik.com/free-vector/blue-circle-with-white-user_145857007.htm#fromView=keyword&page=1&position=0&uuid=8574dadf-f40a-446b-8a47-d2e4cba1dff1&query=Default+profile'),
        ),
    ]
