# Generated by Django 5.2.3 on 2025-11-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_authoraccount_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authoraccount',
            name='image',
            field=models.URLField(default='https://media.istockphoto.com/id/2181567759/vector/round-gray-circle-with-a-simple-human-silhouette-light-gray-shadow-around-the-circle.jpg?s=2048x2048&w=is&k=20&c=pcrT4UtlhWAYNZ_HtgmQFq2lO1QPo0SwOmQHnNDpexs='),
        ),
    ]
