# Generated by Django 5.2.3 on 2025-11-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShareHub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcreate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/images/'),
        ),
        migrations.AlterField(
            model_name='postcreate',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='postcreate',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='posts/videos/'),
        ),
    ]
