# Generated by Django 5.2.3 on 2025-11-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShareHub', '0002_alter_postcreate_image_alter_postcreate_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcreate',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postcreate',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='postcreate',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
