# Generated by Django 5.2.3 on 2025-11-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShareHub', '0003_alter_postcreate_image_alter_postcreate_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcreate',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
