# Generated by Django 5.2.3 on 2025-11-16 14:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShareHub', '0004_alter_postcreate_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('like_post', 'user')},
        ),
    ]
