# Generated by Django 5.2.3 on 2025-11-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShareHub', '0005_alter_like_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcreate',
            name='image',
            field=models.URLField(blank=True, default='https://res.cloudinary.com/ds97wytcs/image/upload/v1725001777/m6idyx9e4rwnmxawgu8o.png', null=True),
        ),
    ]
