# Generated by Django 5.2.3 on 2025-11-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShareHub', '0008_alter_postcreate_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcreate',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
